---
sudo: false
language: ruby
cache: bundler
matrix:
  fast_finish: true
  include:
    - rvm: ruby-head
      gemfile: gemfiles/graphql_edge.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/graphql_edge.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/graphql_1.8.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/graphql_1.7.gemfile
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/graphql_edge.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/graphql_edge.gemfile
before_install:
  - gem update --system
  - gem install bundler -v 1.15.4
